---
# The language that should be used in the plugin
# If your language is missing, you can add it on GitHub!
# Available languages (ISO639-2):
# eng, ara, cat, ces, chi, dan, deu, ell, epo, esp, est, fre, geo, hin, ind, ita, jpn, kor, lit, mar, mas, nld, nor, pol, por, rom, rus, slo, swa, swe, tgl, tha, zho
language: eng
show-startup-icon: false
limit: -1
tool-range: 100
