name: PHPStan

on: [push, pull_request]

jobs:
  phpstan:
    if: "!contains(github.event.head_commit.message, '[phpstan skip]')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Create Vendor Directory
      run: |
        echo Making directory...
        mkdir vendor
        echo Directory made.
    - name: Download virions to vendor
      run: |
        php -f resources/parsepoggit.php > virion_urls.txt
        cat virion_urls.txt
        wget -P vendor --content-disposition -i virion_urls.txt
        rm virion_urls.txt
    - name: Run PHPStan
      uses: larryTheCoder/pmmp-phpstan-action@master
      with:
        phpstan-config: phpstan.neon.dist
